package.json, test/initial-test.test.js
=> add initial-test

app/controllers/home.js, app/routes.js, package.json, test/initial-test.test.js
=> Add initial test

app/controllers/users.js, app/errors.js, app/middlewares/errors.js, app/middlewares/params_validator.js, app/middlewares/users.js, app/routes.js, app/services/users.js, config/index.js, package-lock.json, package.json, pull_request_template.md, test/setup.js, test/users/post.test.js
Endpoint de registro de usuario, validacion de parametros y pedido a authserver para registrarlo.
En el caso que los parametros sean correctos, se envíe la solicitud al authserver, pero ya se encuentre registrado un usuario con el mismo username o email, se devuelve un 400 al appserver pero no se puede detectar por cuál de los dos motivos no se pudo registrar (si falló por username preexistente o por email preexistente)
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/1
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/2
=> Registro usuarios y validacion de parametros

package-lock.json, package.json
fixed missing non dev dependancy "express validator"
=> fixed missing non dev dependancy

app/errors.js, app/services/users.js, test/users/post.test.js
Ahora se envia correctamente el mensaje de error y el internal code como respuesta.
=> Fixed error msg sent as response. Refined tests

app/middlewares/users.js, app/services/users.js, test/users/post.test.js
- Se agrega la verificación de 6 caracteres como mínimo en la contraseña.
=> add 6 min length validation

app/controllers/users.js, app/errors.js, app/middlewares/errors.js, app/middlewares/users.js, app/routes.js, app/services/users.js, test/users/profile.test.js
Endpoint de ver perfil de usuario
Valida que haya token
GET al authserver
Devuelve la info si funciona, 400 si no esta el token, 409 user not found si no se encuentra en la bdd (del auth server), 502 auth server error por cualquier otro error. No sé por qué decidimos hacerlo de esta forma
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/35
=> view profile feature done

app/middlewares/videos.js, app/models/video.js, app/services/videos.js, test/videos/post.test.js
Se recibe username, se manda al media y se guarda en la base de datos en el documento del video como "owner"
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/46
=> Username when upload video

app/controllers/users.js, app/controllers/videos.js, app/models/user.js, app/routes.js, app/services/users.js, app/services/videos.js
Luego de que un usuario se registre en el auth server, se guarda su username en el appserver para futuro uso
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/44
=> username gets saved after signing up

app/errors.js, app/middlewares/authorization.js, app/middlewares/errors.js, app/middlewares/token_validator.js, app/middlewares/users.js, app/middlewares/videos.js, app/routes.js, app/services/users.js, test/videos/post.test.js
Se pregunta al auth server si el token es válido antes de cualquier operación que requiera que el usuario esté logueado
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/41
=> token validation request done

app/controllers/videos.js, app/middlewares/authorization.js, app/middlewares/paging.js, app/middlewares/users.js, app/middlewares/videos.js, app/routes.js, app/serializers/videos.js, app/services/videos.js
- Endpoint GET /videos
- Endpoint GET /videos/me
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/45
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/47
=> Get user videos

app/controllers/videos.js, app/middlewares/videos.js, app/routes.js, app/services/videos.js, test/videos/post.test.js
No se recibe más el username por body, sino que se pide la info del usuario al authserver con el token.
=> refactored POST /videos to get user from auth server

app/middlewares/users.js, app/services/users.js, test/users/login.test.js
Refactor de login para loguearse con username y password porque si no desde la app no se puede obtener el username para consultar el propio perfil
=> refactored login to use username

app/controllers/users.js, app/errors.js, app/mappers/params.js, app/middlewares/errors.js, app/middlewares/users.js, app/models/user.js, app/routes.js, app/serializers/friends.js, app/services/users.js, test/users/friends.test.js
Brancheado de rama "receive friend request"
Listado de friend requests
Listado de friends tambien porque era muy similar
Aceptar y rechazar friend request hecho acá también jaja
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/64
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/66
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/65
=> List friend requests

app/middlewares/users.js
Se agrega la foto de perfil en la edición de perfil.
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/57
=> add user profile pic to edit profile

app/controllers/users.js, app/mappers/params.js, app/mappers/users.js, app/routes.js, app/services/users.js
Refactor del endpoint `PUT /users/me`. `PUT /users/:username`
=> change endpoint put /users/me for /users/:username

app/controllers/users.js, app/services/users.js
Arreglar login para que no rompa con el login transparente
=> fix login and logout

app/controllers/videos.js, app/errors.js, app/middlewares/errors.js, app/middlewares/token_validator.js, app/middlewares/videos.js, app/routes.js, app/services/videos.js, app/utils/push_builder.js
Se borra un video
Se chequea que la persona que lo hace tenga privilegios
Se envia una push al owner avisandole
Ver este pr del auth server donde se hicieron algunos cambios y refactors:
https://github.com/ChutuveG3/ChotuveAuthServer/pull/41
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/83
=> video deletion feature done

app/middlewares/videos.js, app/models/video.js, app/serializers/videos.js, app/services/videos.js, test/videos/post.test.js
- Se agregan latitud y longitud en el post a  /videos.
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/56
=> add location and tests

app/errors.js, app/middlewares/errors.js, app/services/videos.js
Added check to see if video exists before deleting and responds with 409
=> added missing check when deleting video

app/controllers/videos.js, app/middlewares/videos.js, app/routes.js, app/serializers/videos.js
Devolver toda la info de un video
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/99
=> Refactor videos

app/controllers/videos.js, app/routes.js, app/serializers/videos.js, app/services/ranker.js, app/services/videos.js, package-lock.json, package.json
[Change!] Describe your feature, problems you had, notes, improvements and others.
[Change!] List any known issue of the feature you are implementing.
[Change!] Link to the associated Trello card.
=> Recommendations

README.md, app/controllers/users.js, app/controllers/videos.js, app/middlewares/users.js, app/routes.js, app/services/users.js, test/mocks/authorization.js, test/users/delete.test.js, test/videos/delete.test.js
Se borra un usuario
Se agregan tests de borrar video también, que faltaban
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/112
=> delete user done

app.js, package-lock.json, package.json
Se agrega un monitor de métricas.
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/109
=> add metrics

app/controllers/users.js, app/errors.js, app/middlewares/errors.js, app/middlewares/users.js, app/routes.js, app/services/users.js
Ambos enpoints: recupero y configuracion de contraseña
https://app.zenhub.com/workspaces/chotuve---grupo-3-5ea5f06b270a794f8ced01b5/issues/chutuveg3/chotuveappserver/113
=> password recovery done

app/controllers/users.js, app/mappers/users.js, app/middlewares/users.js, app/routes.js, app/utils/push_builder.js
=> Message notification

app/controllers/videos.js, app/models/video.js, app/serializers/videos.js, app/services/videos.js
Se agrega cantidad de vistas a los videos y se devuelve en home, ver videos de otro usuario y ver un video
=> added number of views to video
